# Exported from Render on 2026-01-17T08:01:27Z
version: "1"
projects:
- name: Django_IntervjuBot
  environments:
  - name: Production
    services:
    - type: web
      name: IntervjuBot_Django
      runtime: python
      repo: https://github.com/RavSeime/IntervjuBot_Django
      plan: starter
      envVars:
      - key: LANGSMITH_PROJECT
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_ENDPOINT
        sync: false
      - key: LANGSMITH_TRACING
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: SECRET_KEY
        sync: false
      region: frankfurt
      buildCommand: ./build.sh
      startCommand: cd django_stack && gunicorn django_stack.wsgi:application
      autoDeployTrigger: "off"
