# Generated by Django 5.2.8 on 2025-12-02 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=100)),
                ('params', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.CharField(max_length=100)),
                ('responses', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.surveyparams')),
            ],
            options={
                'unique_together': {('survey', 'respondent_id')},
            },
        ),
        migrations.AddConstraint(
            model_name='surveyparams',
            constraint=models.UniqueConstraint(fields=('user', 'survey_name'), name='unique_user_survey'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyparams',
            unique_together={('user', 'survey_name')},
        ),
    ]
